### ISSUE TITLE
bug: "main" invalid in package.json

### ISSUE THREAD

**Issue by 3runoDesign** [indentjs/objectorarray#6] opened 2021-04-29 12:36 UTC
https://github.com/indentjs/objectorarray/blob/debc681042391f9af620d7f26f70a46511f729b3/package.json#L5

**Comment by ath0mas** [comment] 2021-04-29 20:15
Duplicate of #3, and PR #4 to fix this

**Closed as completed** 2021-04-30 15:03 UTC
